### PR TITLE
Prevent PaymentController#expired from expiring Used Payments

### PR DESCRIPTION
**Pull request by bcassedy**

### CODE REVIEW

**Comment by taylorsatula** [comment]
I literally don't work for this company anymore. ("work" is a very vague
term)

**Comment by bcassedy** [comment]
If you're no longer interested in these notifications, I suggest clicking Unwatch next to this repo here: https://github.com/watching

**Comment by taylorsatula** [comment]
Will do.

Someone also should remove me from all the sensitive documents with login
information and credit card information too. Nobody cleaned up after I
left.............

Just a friendly reminder.

**Comment by kumario** [comment]
Thanks @bcassedy. Feel free to sabotage the project @taylorsatula! :-)

**Pull request merged**
